maintainer       'FlatStack'
maintainer_email 'support@flatstack.com'
license          'All rights reserved'
description      'Installs/Configures FlatStack Chef Cookbooks'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.3'

depends 'ohai', '1.1.8'
depends 'apt', '1.9.0'
depends 'hostname', '0.0.4'
depends 'vim', '1.0.2'
depends 'git', '2.3.0'
depends 'rbenv', '1.4.1'
depends 'htop', '1.0.0'
depends 'user', '0.3.0'
depends 'nginx', '1.0.0'
depends 'database', '1.3.12'
depends 'mysql', '2.1.2'
depends 'postgresql', '2.2.2'
depends 'postfix', '2.1.4'
depends 'logentries', '0.1.0'
